SITES = {
    "GitHub": "https://github.com/{username}",
    "GitLab": "https://gitlab.com/{username}",
    "Reddit": "https://www.reddit.com/user/{username}",
    "Pinterest": "https://www.pinterest.com/{username}/",
    "TikTok": "https://www.tiktok.com/@{username}",
    "Twitch": "https://www.twitch.tv/{username}",
    "Steam": "https://steamcommunity.com/id/{username}",
    "Medium": "https://medium.com/@{username}",
    "Dev.to": "https://dev.to/{username}",
    "StackOverflow": "https://stackoverflow.com/users/{username}",
    "Kaggle": "https://www.kaggle.com/{username}",
    "CodePen": "https://codepen.io/{username}",
    "Replit": "https://replit.com/@{username}",
    "HackerOne": "https://hackerone.com/{username}",
    "Bugcrowd": "https://bugcrowd.com/{username}",
    "Roblox": "https://www.roblox.com/users/{username}/profile",
    "SoundCloud": "https://soundcloud.com/{username}",
    "Vimeo": "https://vimeo.com/{username}",
    "Imgur": "https://imgur.com/user/{username}",
    "Flickr": "https://www.flickr.com/people/{username}",
}